name: shake_search
description: A take home test for Pulley

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  bloc: ^8.0.3
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  expandable: ^5.0.1
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/shake.png

